version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: loanguru
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  loanguru:
    image: openjdk:21-jdk
    volumes:
      - ./build/libs/loanguru-0.0.1-SNAPSHOT.jar:/app/app.jar
    command: ["java", "-jar", "/app/app.jar"]
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  postgres_data: